use crate::state::Focus;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ScrollDirection {
    Up,
    Down,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Action {
    Noop,
    Quit,
    NextFocus,
    PreviousFocus,
    MoveDown,
    MoveUp,
    PageDown,
    PageUp,
    ScrollDiffLeft,
    ScrollDiffRight,
    ScrollDiff {
        direction: ScrollDirection,
        lines: usize,
    },
    NextHunk,
    PreviousHunk,
    ToggleDiffLineNumbers,
    ToggleDiffLayout,
    Refresh,
    GoToFirst,
    GoToLast,
    FocusPanel(Focus),
    ToggleCollapsed,
    NextFile,
    PreviousFile,
    ToggleSidebar,
    ToggleCommandPalette,
    ToggleThemeSelector,
    ToggleThemeFilter,
    ToggleFileFinder,
    ToggleCommitsFinder,
    ToggleCommitsFinderFocus,
    FocusCommitsFinderList,
    SelectCommitsFinderResult,
    ResetToCurrentChanges,
    CommitsFinderInput(char),
    CommitsFinderBackspace,
    CommitsFinderClear,
    SelectFileFinderResult,
    RunSelectedCommand,
    SelectTheme,
    OpenEditor,
    SelectTreeRow(usize),
    FileFinderInput(char),
    FileFinderBackspace,
    FileFinderClear,
    ToggleReviewed,
    ToggleFileCollapse,
}
